version: "3"
services:
  web:
    platform: linux/amd64
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src/backend

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tododb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql:/var/lib/mysql
